export const LIST_PROJECTS_CURRENT = 'LIST_PROJECTS_CURRENT';
export const LINK_SECTION = 'LINK_SECTION';
export const MENU = 'MENU';
export const FILTER_MASTERPIECES = 'FILTER_MASTERPIECES';
export const OUR_MASTERPIECES = 'OUR_MASTERPIECES';
